// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRmA-g5i0SmEi-TI3fPYzoKObgq8j0Xmk',
    appId: '1:672776830370:web:d460d4002063eefae906fb',
    messagingSenderId: '672776830370',
    projectId: 'akilliy',
    authDomain: 'akilliy.firebaseapp.com',
    storageBucket: 'akilliy.firebasestorage.app',
    measurementId: 'G-QPKSRQQ17C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkDEmJoUKWWqfddxBkx_Hka3V-K2u2LjI',
    appId: '1:672776830370:android:9d28c4718583c4dbe906fb',
    messagingSenderId: '672776830370',
    projectId: 'akilliy',
    storageBucket: 'akilliy.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-Z9CRkkcAdtfsaK1sTMTsIMHJ1owiDW4',
    appId: '1:672776830370:ios:5ca3aed610a11af3e906fb',
    messagingSenderId: '672776830370',
    projectId: 'akilliy',
    storageBucket: 'akilliy.firebasestorage.app',
    iosBundleId: 'com.example.flutterQryoklamasistemi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-Z9CRkkcAdtfsaK1sTMTsIMHJ1owiDW4',
    appId: '1:672776830370:ios:5ca3aed610a11af3e906fb',
    messagingSenderId: '672776830370',
    projectId: 'akilliy',
    storageBucket: 'akilliy.firebasestorage.app',
    iosBundleId: 'com.example.flutterQryoklamasistemi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDRmA-g5i0SmEi-TI3fPYzoKObgq8j0Xmk',
    appId: '1:672776830370:web:a4a7032efb5c9a2ae906fb',
    messagingSenderId: '672776830370',
    projectId: 'akilliy',
    authDomain: 'akilliy.firebaseapp.com',
    storageBucket: 'akilliy.firebasestorage.app',
    measurementId: 'G-W26TX702TV',
  );

}